In [55]:
import pandas as pd
import numpy as np

In [6]:
fake = pd.read_csv(r'C:\Users\kartik.nerwal\Downloads\archive/Fake.csv')
real = pd.read_csv(r'C:\Users\kartik.nerwal\Downloads\archive/True.csv')


In [10]:
fake['Class'] = 0
real['Class'] = 1

In [11]:
fake.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date  Class  
0  December 31, 2017      0  
1  December 31, 2017      0  
2  December 30, 2017      0  
3  December 29, 2017      0  
4  December 25, 2017      0

In [12]:
real.head()

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   
2  Senior U.S. Republican senator: 'Let Mr. Muell...   
3  FBI Russia probe helped by Australian diplomat...   
4  Trump wants Postal Service to charge 'much mor...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   

                 date  Class  
0  December 31, 2017       1  
1  December 29, 2017       1  
2  December 31, 2017       1  
3  December 30, 2017       1  
4  December 29, 2017       1

In [13]:
df = pd.DataFrame()
df = pd.concat([df,fake,real])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44898 entries, 0 to 21416
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   Class    44898 non-null  int64 
dtypes: int64(1), object(4)
memory usage: 2.1+ MB


In [17]:
df = df.dropna()

In [22]:
X = df['title']
y = df['Class']

In [23]:
X.shape

(44898,)

In [24]:
import tensorflow as tf

In [53]:
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [27]:
vocab_size = 5000

In [28]:
messages = X.copy()

In [37]:
messages.reset_index(inplace=True, drop=True)

In [30]:
import nltk
import re
from nltk.corpus import stopwords

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kartik.nerwal\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [32]:
from nltk.stem.porter import PorterStemmer

In [38]:
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages[i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [46]:
onehot_repr = [one_hot(words, vocab_size) for words in corpus]

In [47]:
onehot_repr

[[426, 721, 354, 4959, 4626, 4162, 2866, 511, 1245],
 [4772, 2704, 721, 2550, 3058, 3672, 1180, 3117],
 [479, 1877, 717, 4115, 4525, 2674, 3079, 4147, 1086, 2337],
 [721, 2325, 1342, 1007, 1674, 4620, 3220, 3751],
 [803, 2967, 1303, 426, 721, 1493, 4335],
 [2558, 3608, 1513, 4707, 432, 4351, 1700, 4593, 3751],
 [159, 2288, 1064, 721, 3262, 172, 4724, 840, 1222, 2808],
 [721, 1659, 3835, 2558, 4739, 2736, 2262, 4240, 1634, 276],
 [3748, 2295, 840, 1010, 721, 3348, 1292, 868, 2336, 2093, 3314, 2485, 1523],
 [4936, 4794, 4626, 4986, 721, 4092, 1466, 765, 4255, 4095, 3685],
 [2983, 588, 2335, 2793, 2572, 388, 442, 4507],
 [4936, 4498, 3369, 4772, 4688, 3866, 4564, 3456, 1071, 1976, 1736],
 [442, 3184, 721, 1719, 1227, 1752, 4173, 2429],
 [4936, 4451, 2668, 288, 4743, 4315, 721, 1365, 1063, 2933],
 [774, 2060, 3869, 4537, 2374, 4699, 4688, 2204, 506, 2262],
 [3045, 1160, 721, 1303, 3622, 1305, 3007, 1938, 3002, 3681],
 [4525, 4707, 1488, 2060, 4626, 721, 4171, 4099, 349],
 [2398, 2622, 2312

In [48]:
sent_length = 20
embedding_docs = pad_sequences(onehot_repr, padding='pre', maxlen = sent_length)

In [49]:
embedding_docs

array([[   0,    0,    0, ..., 2866,  511, 1245],
       [   0,    0,    0, ..., 3672, 1180, 3117],
       [   0,    0,    0, ..., 4147, 1086, 2337],
       ...,
       [   0,    0,    0, ..., 2283, 4115, 3836],
       [   0,    0,    0, ..., 2967, 2832, 3452],
       [   0,    0,    0, ...,  765, 3672, 2087]])

In [50]:
len(embedding_docs)

44898

In [51]:
embedding_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        426,  721,  354, 4959, 4626, 4162, 2866,  511, 1245])

In [89]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(vocab_size, embedding_vector_features, input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(100, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout_6 (Dropout)         (None, 20, 40)            0         
                                                                 
 lstm_3 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_7 (Dropout)         (None, 100)               0         
                                                                 
 dense_5 (Dense)             (None, 100)               10100     
                                                                 
 dense_6 (Dense)             (None, 1)                 101       
                                                                 
Total params: 266601 (1.02 MB)
Trainable params: 26660

In [84]:
final_X = np.array(embedding_docs)
final_y = np.array(y)

In [85]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(final_X, final_y, test_size=0.3, random_state=0)

In [91]:
history = model.fit(X_train, y_train, validation_data = (X_test, y_test), epochs=10, batch_size=64)

Epoch 1/10
492/492 [==============================] - 13s 27ms/step - loss: 0.1987 - accuracy: 0.9186 - val_loss: 0.1598 - val_accuracy: 0.9376
Epoch 2/10
492/492 [==============================] - 13s 26ms/step - loss: 0.1244 - accuracy: 0.9511 - val_loss: 0.1457 - val_accuracy: 0.9425
Epoch 3/10
492/492 [==============================] - 13s 27ms/step - loss: 0.0955 - accuracy: 0.9639 - val_loss: 0.1545 - val_accuracy: 0.9403
Epoch 4/10
492/492 [==============================] - 16s 33ms/step - loss: 0.0812 - accuracy: 0.9682 - val_loss: 0.1665 - val_accuracy: 0.9396
Epoch 5/10
492/492 [==============================] - 12s 24ms/step - loss: 0.0698 - accuracy: 0.9741 - val_loss: 0.1754 - val_accuracy: 0.9405
Epoch 6/10
492/492 [==============================] - 12s 24ms/step - loss: 0.0622 - accuracy: 0.9779 - val_loss: 0.1881 - val_accuracy: 0.9393
Epoch 7/10
492/492 [==============================] - 12s 25ms/step - loss: 0.0535 - accuracy: 0.9804 - val_loss: 0.1989 - val_accuracy:

In [120]:
y_pred = model.predict(X_test)

  1/421 [..............................] - ETA: 10s

421/421 [==============================] - 2s 4ms/step


In [68]:
from sklearn.metrics import confusion_matrix

In [121]:
y_pred

array([[9.9998766e-01],
       [9.9974155e-01],
       [9.9999893e-01],
       ...,
       [9.9478507e-01],
       [1.5025238e-08],
       [2.6786340e-09]], dtype=float32)

In [126]:
y_pred = [1 if i>=0.5 else 0 for i in y_pred ]

In [127]:
confusion_matrix(y_test, y_pred)

array([[6457,  568],
       [ 266, 6179]], dtype=int64)

In [128]:
from sklearn.metrics import accuracy_score

In [129]:
accuracy_score(y_test, y_pred)

0.9380846325167038