In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of juice','the glass of milk','the cup of tea','i am a good boy','i am a good develope',
        'understand the meaning of words','your videos are good']

In [3]:
sent

['the glass of juice',
 'the glass of milk',
 'the cup of tea',
 'i am a good boy',
 'i am a good develope',
 'understand the meaning of words',
 'your videos are good']

In [7]:
# vocab size
voc_size = 10000

In [9]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[9236, 6831, 3797, 5248], [9236, 6831, 3797, 1123], [9236, 5968, 3797, 6757], [5356, 7431, 6235, 5128, 189], [5356, 7431, 6235, 5128, 2107], [8219, 9236, 4128, 3797, 8418], [9563, 4555, 7221, 5128]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9236 6831 3797 5248]
 [   0    0    0    0 9236 6831 3797 1123]
 [   0    0    0    0 9236 5968 3797 6757]
 [   0    0    0 5356 7431 6235 5128  189]
 [   0    0    0 5356 7431 6235 5128 2107]
 [   0    0    0 8219 9236 4128 3797 8418]
 [   0    0    0    0 9563 4555 7221 5128]]


In [14]:
dim = 10

In [21]:
Embedding?

Init signature:
Embedding(
    input_dim,
    output_dim,
    embeddings_initializer='uniform',
    embeddings_regularizer=None,
    activity_regularizer=None,
    embeddings_constraint=None,
    mask_zero=False,
    input_length=None,
    sparse=False,
    **kwargs,
)
Docstring:     
Turns positive integers (indexes) into dense vectors of fixed size.

e.g. `[[4], [20]] -> [[0.25, 0.1], [0.6, -0.2]]`

This layer can only be used on positive integer inputs of a fixed range. The
`tf.keras.layers.TextVectorization`, `tf.keras.layers.StringLookup`,
and `tf.keras.layers.IntegerLookup` preprocessing layers can help prepare
inputs for an `Embedding` layer.

This layer accepts `tf.Tensor`, `tf.RaggedTensor` and `tf.SparseTensor`
input.

Example:

>>> model = tf.keras.Sequential()
>>> model.add(tf.keras.layers.Embedding(1000, 64, input_length=10))
>>> # The model will take as input an integer matrix of size (batch,
>>> # input_length), and the largest integer (i.e. word index) in the input
>>> 

In [16]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 234ms/step


array([[[ 4.75700982e-02, -2.91370992e-02, -1.07466355e-02,
         -2.19163653e-02,  4.30633686e-02, -1.92885995e-02,
         -2.87541281e-02, -2.00037248e-02, -2.66027208e-02,
         -2.07676645e-02],
        [ 4.75700982e-02, -2.91370992e-02, -1.07466355e-02,
         -2.19163653e-02,  4.30633686e-02, -1.92885995e-02,
         -2.87541281e-02, -2.00037248e-02, -2.66027208e-02,
         -2.07676645e-02],
        [ 4.75700982e-02, -2.91370992e-02, -1.07466355e-02,
         -2.19163653e-02,  4.30633686e-02, -1.92885995e-02,
         -2.87541281e-02, -2.00037248e-02, -2.66027208e-02,
         -2.07676645e-02],
        [ 4.75700982e-02, -2.91370992e-02, -1.07466355e-02,
         -2.19163653e-02,  4.30633686e-02, -1.92885995e-02,
         -2.87541281e-02, -2.00037248e-02, -2.66027208e-02,
         -2.07676645e-02],
        [ 2.81637423e-02,  4.60806228e-02,  3.76367830e-02,
          3.72111797e-04, -2.74699088e-02,  2.52400897e-02,
          4.86927517e-02,  1.66208036e-02,  3.639570

In [20]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 32ms/step
[[ 4.75700982e-02 -2.91370992e-02 -1.07466355e-02 -2.19163653e-02
   4.30633686e-02 -1.92885995e-02 -2.87541281e-02 -2.00037248e-02
  -2.66027208e-02 -2.07676645e-02]
 [ 4.75700982e-02 -2.91370992e-02 -1.07466355e-02 -2.19163653e-02
   4.30633686e-02 -1.92885995e-02 -2.87541281e-02 -2.00037248e-02
  -2.66027208e-02 -2.07676645e-02]
 [ 4.75700982e-02 -2.91370992e-02 -1.07466355e-02 -2.19163653e-02
   4.30633686e-02 -1.92885995e-02 -2.87541281e-02 -2.00037248e-02
  -2.66027208e-02 -2.07676645e-02]
 [ 4.75700982e-02 -2.91370992e-02 -1.07466355e-02 -2.19163653e-02
   4.30633686e-02 -1.92885995e-02 -2.87541281e-02 -2.00037248e-02
  -2.66027208e-02 -2.07676645e-02]
 [ 2.81637423e-02  4.60806228e-02  3.76367830e-02  3.72111797e-04
  -2.74699088e-02  2.52400897e-02  4.86927517e-02  1.66208036e-02
   3.63957025e-02 -4.52031940e-03]
 [ 4.51269783e-02  3.31583731e-02  2.85263918e-02 -8.79652798e-05
  -2.80114543e-02  2.95440219e-02 -4.82885242e-